### Librerías a utilizar

In [3]:
import pandas as pd
import duckdb
import os

Se crea un diccionario con los nombres de archivos para luego cargar las tablas en la base de datos

In [21]:
data_folder = 'Data'

tables = os.listdir(data_folder)

files = {}
for t in tables:
    if t[-3:] == 'csv':
        files[t[:-4]] = t

Se cargan las tablas a duckDB

In [23]:
con = duckdb.connect()  # o duckdb.connect('mi_base.duckdb') para persistir



for table, file in files.items():
    con.execute(f"""
        CREATE TABLE {table} AS 
        SELECT * FROM read_csv_auto('Data/{file}')
    """)

# Verificar qué tablas quedaron cargadas
con.execute("SHOW TABLES").fetchdf()

                             name
0                         activos
1                 evento_repuesto
2                  evento_tecnico
3           eventos_mantenimiento
4                   log_operativo
5                      mediciones
6                         ordenes
7   plan_mantenimiento_preventivo
8                         plantas
9               repuestos_insumos
10                       tecnicos
11                    tipo_activo
12                    tipo_cambio
13          tipo_evento_operativo
14                     tipo_falla
15                  tipo_medicion

In [36]:
activos_10 = con.execute(
    f"""
    SELECT * FROM tipo_activo LIMIT 10
    """
).fetchdf()

In [37]:
activos_10

   tipo_activo_id               nombre            categoria
0               1          Área/Sector          Estructural
1               2     Bomba centrífuga  Hidráulico/Mecánico
2               3     Bomba hidráulica           Hidráulico
3               4   Motor eléctrico CC            Eléctrico
4               5   Motor eléctrico AC            Eléctrico
5               6         Motor diesel           Combustión
6               7     Motor hidráulico           Hidráulico
7               8        Transformador            Eléctrico
8               9  Generador eléctrico            Eléctrico
9              10    Pistón hidráulico           Hidráulico