## Librerías y Configuraciones previas

In [1]:
import pandas as pd
import duckdb
import os
import matplotlib.pyplot as plt

#Para compatibilidad de versiones de wcwidth con jupysql
import wcwidth
if not hasattr(wcwidth, 'width'):
    wcwidth.width = wcwidth.wcswidth  # Crea un alias hacia la función de conteo de strings

Se genera la conexión con la base de datos (en memoria)

In [2]:
# Se crea la conexión con duckdb con persistencia en el archivo data.duckdb
conn = duckdb.connect('data.duckdb') # o duckdb.connect('data.duckdb') para persistir

Usando jupysql previamente instalada en el ambiente con (pip install jupysql duckdb-engine)

In [3]:
# Carga y configura la extensión
%load_ext sql

# referencia conn con duckdb dentro de %%sql
%sql conn --alias duckdb

# Configuraciones de jupysql para que las salidas generen un dataframe de pandas y que no emitan otros detalles
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

Se crea un diccionario con los nombres de archivos para luego cargar las tablas en la base de datos

In [23]:
data_folder = 'Data'

files = os.listdir(data_folder)

tables = {}
for f in files:
    if f[-3:] == 'csv':
        tables[f[:-4]] = f

dfs = {}

for table, file in tables.items():
    try:
        conn.execute(f"""
            CREATE TABLE {table} AS 
            SELECT * FROM read_csv_auto('Data/{file}')
        """)
    except:
        print('Error al cargar las tablas o tablas cargadas previamente')
        break

for table, file in tables.items():
    #Se generan tambien dos data frames para utilizar pandas
    dfs[table] = pd.read_csv(f'Data/{file}')

# Verificar qué tablas quedaron cargadas
conn.execute("SHOW TABLES").fetchdf()

Error al cargar las tablas o tablas cargadas previamente

                             name
0                         activos
1                 evento_repuesto
2                  evento_tecnico
3           eventos_mantenimiento
4                   log_operativo
5                      mediciones
6                         ordenes
7   plan_mantenimiento_preventivo
8                         plantas
9               repuestos_insumos
10                       tecnicos
11                    tipo_activo
12                    tipo_cambio
13          tipo_evento_operativo
14                     tipo_falla
15                  tipo_medicion

## Análisis Exploratorio

In [24]:
%%sql
SELECT * FROM log_operativo LIMIT 5;

,log_id,planta_id,activo_id,fecha_hora,tipo_evento_id,descripcion
0,1,4,109.0,2024-01-01 02:22:30.553267,13,sin novedad
1,2,1,NaN,2024-01-01 06:00:00.000000,20,normal
2,3,5,NaN,2024-01-01 06:00:00.000000,21,ok
3,4,3,63.0,2024-01-01 12:16:51.742203,11,ok.
4,5,1,NaN,2024-01-01 14:00:00.000000,20,ok

In [25]:
dfs['log_operativo'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10349 entries, 0 to 10348
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   log_id          10349 non-null  int64
 1   planta_id       10349 non-null  int64
 2   activo_id       4707 non-null   float64
 3   fecha_hora      10349 non-null  object
 4   tipo_evento_id  10349 non-null  int64
 5   descripcion     8294 non-null   object
dtypes: float64(1), int64(3), object(2)
memory usage: 485.2+ KB

Explorar tabla **tipo_activo**

In [7]:

%%sql

SELECT tipo_activo_id, 
        COUNT(*),
FROM tipo_activo
GROUP BY tipo_activo_id
HAVING COUNT(*) > 1;

Empty DataFrame
Columns: [tipo_activo_id, count_star()]
Index: []

Explorar tabla **activos**