## Librerías y Configuraciones previas

In [1]:
import pandas as pd
import duckdb
import os
import matplotlib.pyplot as plt

#Para compatibilidad de versiones de wcwidth con jupysql
import wcwidth
if not hasattr(wcwidth, 'width'):
    wcwidth.width = wcwidth.wcswidth  # Crea un alias hacia la función de conteo de strings

Se genera la conexión con la base de datos (en memoria)

In [2]:
# Se crea la conexión con duckdb con persistencia en el archivo data.duckdb
conn = duckdb.connect('data.duckdb') # o duckdb.connect('data.duckdb') para persistir

Usando jupysql previamente instalada en el ambiente con (pip install jupysql duckdb-engine)

In [3]:
# Carga y configura la extensión
%load_ext sql

# referencia conn con duckdb dentro de %%sql
%sql conn --alias duckdb

# Configuraciones de jupysql para que las salidas generen un dataframe de pandas y que no emitan otros detalles
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

Se crea un diccionario con los nombres de archivos para luego cargar las tablas en la base de datos

In [4]:
data_folder = 'Data'

files = os.listdir(data_folder)

tables = {}
for f in files:
    if f[-3:] == 'csv':
        tables[f[:-4]] = f

dfs = {}

for table, file in tables.items():
    try:
        conn.execute(f"""
            CREATE TABLE {table} AS 
            SELECT * FROM read_csv_auto('Data/{file}')
        """)
    except:
        print('Error al cargar las tablas o tablas cargadas previamente')
        break

for table, file in tables.items():
    #Se generan tambien dos data frames para utilizar pandas
    dfs[table] = pd.read_csv(f'Data/{file}')

# Verificar qué tablas quedaron cargadas
conn.execute("SHOW TABLES").fetchdf()

Error al cargar las tablas o tablas cargadas previamente

                             name
0                         activos
1                 evento_repuesto
2                  evento_tecnico
3           eventos_mantenimiento
4                   log_operativo
5                      mediciones
6                         ordenes
7   plan_mantenimiento_preventivo
8                         plantas
9               repuestos_insumos
10                       tecnicos
11                    tipo_activo
12                    tipo_cambio
13          tipo_evento_operativo
14                     tipo_falla
15                  tipo_medicion

## Análisis Exploratorio

Se comienza explorando las tablas

In [5]:
%%sql
SELECT * FROM eventos_mantenimiento LIMIT 5;

,evento_id,activo_id,orden_id,tipo_mantenimiento,tipo_falla_id,fecha_hora_inicio,fecha_hora_fin,genero_paro_planta,descripcion
0,1,2,NaN,correctivo,10.0,2024-04-09 09:03:05.300383,2024-04-10 02:52:34.853051,False,PARADA IMPREVISTA
1,2,2,NaN,correctivo,12.0,2024-07-12 13:56:37.481892,2024-07-13 00:56:41.368120,False,detectado ruido anormal
2,3,2,NaN,correctivo,5.0,2024-12-28 04:43:18.524417,2024-12-28 15:01:13.238261,True,reparación de urgencia
3,4,2,NaN,correctivo,1.0,2025-03-30 08:08:50.877964,2025-03-31 07:09:18.830599,False,pérdida reportada por turno noche
4,5,2,NaN,correctivo,1.0,2025-04-17 21:08:41.514886,2025-04-18 05:15:48.092750,False,"falla detectada por operador, se interviene"

In [6]:
dfs['eventos_mantenimiento'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2673 entries, 0 to 2672
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   evento_id           2673 non-null   int64
 1   activo_id           2673 non-null   int64
 2   orden_id            2354 non-null   float64
 3   tipo_mantenimiento  2673 non-null   object
 4   tipo_falla_id       2529 non-null   float64
 5   fecha_hora_inicio   2673 non-null   object
 6   fecha_hora_fin      2673 non-null   object
 7   genero_paro_planta  2673 non-null   bool
 8   descripcion         2673 non-null   object
dtypes: bool(1), float64(2), int64(2), object(4)
memory usage: 169.8+ KB

In [24]:
%%sql
SELECT tipo_mantenimiento, COUNT(*) AS count,
COUNT(*) / SUM(COUNT(*)) OVER() AS proportion
FROM eventos_mantenimiento GROUP BY tipo_mantenimiento;

  tipo_mantenimiento  count  proportion
0         correctivo    319    0.119342
1         preventivo   2354    0.880658

Existen dos columnas con valores nulos, orden_id, y tipo de falla id

In [12]:
%%sql
SELECT * FROM eventos_mantenimiento WHERE orden_id IS NULL;

,evento_id,activo_id,orden_id,tipo_mantenimiento,tipo_falla_id,fecha_hora_inicio,fecha_hora_fin,genero_paro_planta,descripcion
0,1,2,NaN,correctivo,10.0,2024-04-09 09:03:05.300383,2024-04-10 02:52:34.853051,False,PARADA IMPREVISTA
1,2,2,NaN,correctivo,12.0,2024-07-12 13:56:37.481892,2024-07-13 00:56:41.368120,False,detectado ruido anormal
2,3,2,NaN,correctivo,5.0,2024-12-28 04:43:18.524417,2024-12-28 15:01:13.238261,True,reparación de urgencia
3,4,2,NaN,correctivo,1.0,2025-03-30 08:08:50.877964,2025-03-31 07:09:18.830599,False,pérdida reportada por turno noche
4,5,2,NaN,correctivo,1.0,2025-04-17 21:08:41.514886,2025-04-18 05:15:48.092750,False,"falla detectada por operador, se interviene"
...,...,...,...,...,...,...,...,...,...
314,315,145,NaN,correctivo,10.0,2024-10-25 10:36:41.635365,2024-10-26 04:07:36.648021,False,para por alarma
315,316,145,NaN,correctivo,1.0,2025-04-19 16:14:00.422308,2025-04-20 10:38:54.199922,False,pérdida reportada por turno noche
316,317,146,NaN,correctivo,5.0,2024-06-14 09:24:32.468705,2024-06-15 06:12:05.307235,True,detectado ruido anormal
317,318,146,NaN,correctivo,5.0,2025-05-20 17:14:10.388440,2025-05-21 07:42:45.450187,False,detectado ruido anormal
318,319,146,NaN,correctivo,9.0,2025-10-28 06:40:25.597032,2025-10-29 05:46:24.205408,False,falla en arranque

In [26]:
%%sql
SELECT COUNT(*) / (SELECT COUNT(*) FROM eventos_mantenimiento) AS 'order_id null proportion' FROM eventos_mantenimiento WHERE  orden_id IS NULL;

   order_id null proportion
0                  0.119342

Hay 319 filas con valor nulo en orden_id y representan el 12% de los registros.

Aparentemente todos los valores nulos de orden corresponden a mantenimientos correctivos, con lo cual se podría asumir que no se emiten órdenes para mantenimientos correctivos, a continuación se chequea si existen otros casos con orden_id nulo.

In [13]:
%%sql
SELECT * FROM eventos_mantenimiento WHERE orden_id IS NULL
AND tipo_mantenimiento != 'correctivo';

Empty DataFrame
Columns: [evento_id, activo_id, orden_id, tipo_mantenimiento, tipo_falla_id, fecha_hora_inicio, fecha_hora_fin, genero_paro_planta, descripcion]
Index: []

Todos los valores nulos de orden_id corresponden a mantenimientos del tipo correctivo.

In [14]:
%%sql
SELECT * FROM eventos_mantenimiento WHERE tipo_falla_id IS NULL;

,evento_id,activo_id,orden_id,tipo_mantenimiento,tipo_falla_id,fecha_hora_inicio,fecha_hora_fin,genero_paro_planta,descripcion
0,7,3,NaN,correctivo,NaN,2025-09-27 23:37:46.727753,2025-09-29 22:51:13.610357,True,intervención según diagnóstico previo
1,16,6,NaN,correctivo,NaN,2024-04-08 22:10:14.878510,2024-04-09 21:26:32.431613,False,para por alarma
2,27,7,NaN,correctivo,NaN,2025-01-28 23:25:37.492956,2025-01-29 21:00:46.192766,True,pérdida reportada por turno noche
3,37,12,NaN,correctivo,NaN,2024-11-11 12:48:43.777147,2024-11-11 19:46:58.704409,True,s/observaciones
4,64,24,NaN,correctivo,NaN,2024-10-19 15:13:17.855095,2024-10-20 14:05:55.592718,True,s/observaciones
...,...,...,...,...,...,...,...,...,...
139,2587,136,2774.0,preventivo,NaN,2025-06-17 14:06:43.855919,2025-06-17 17:04:25.045978,False,"rutina realizada, todo en orden"
140,2604,144,2796.0,preventivo,NaN,2025-04-04 11:34:26.659511,2025-04-04 15:09:16.705840,True,tarea de rutina según plan
141,2618,146,2816.0,preventivo,NaN,2024-11-18 15:06:01.996171,2024-11-18 18:44:53.743641,False,cumplido
142,2628,146,2828.0,preventivo,NaN,2025-11-14 11:34:41.458738,2025-11-14 13:41:34.409370,False,s/n
143,2639,47,2843.0,preventivo,NaN,2025-09-14 13:34:10.226624,2025-09-14 19:23:59.584506,False,cumplido

Los tipos de falla nulos aparecen en ambos tipos de mantenimiento, puede ser que esos mantenimientos no hayan sido clasificados dentro de fallas comunes

Se analizan los tipos de falla por tipo de activo y categoría

In [43]:
%%sql

tipo_falla_activo <<

SELECT 
em.tipo_mantenimiento,
em.tipo_falla_id, 
tf.descripcion AS tipo_falla, 
em.descripcion,
ta.nombre AS nombre_activo,
ta.categoria AS categoria_activo
FROM eventos_mantenimiento em 
LEFT JOIN tipo_falla tf ON tf.tipo_falla_id = em.tipo_falla_id
LEFT JOIN activos a ON em.activo_id = a.activo_id
LEFT JOIN tipo_activo ta ON a.tipo_activo_id = ta.tipo_activo_id;

In [48]:
tipo_falla_activo.sample(5)

,tipo_mantenimiento,tipo_falla_id,tipo_falla,descripcion,nombre_activo,categoria_activo
1406,preventivo,14.0,Mantenimiento programado (sin falla),cumplido,Cinta transportadora,Mecánico
129,correctivo,6.0,Falla de aislación,detectado ruido anormal,Motor eléctrico AC,Eléctrico
2199,preventivo,14.0,Mantenimiento programado (sin falla),pendiente revisión adicional,Puente grúa,Mecánico
840,preventivo,14.0,Mantenimiento programado (sin falla),se realizó tarea programada,Motor eléctrico CC,Eléctrico
1946,correctivo,NaN,None,para por alarma,Puente grúa,Mecánico

Conteo de valores en caso de tipo_falla_id nula

In [40]:
tipo_falla_activo[tipo_falla_activo['tipo_falla_id'].isna()]['nombre_activo'].value_counts()

nombre_activo
Puente grúa                       29
Motor eléctrico AC                21
Malacate                          20
Motor diesel                      15
Cinta transportadora              14
Generador eléctrico               13
Electroválvula                     7
Motor eléctrico CC                 6
Variador de frecuencia             4
Motor hidráulico                   3
Bomba hidráulica                   3
Pistón hidráulico                  3
Tablero distribución eléctrica     2
Válvula esclusa                    2
Transformador                      1
Tablero de control                 1
Name: count, dtype: int64

In [50]:
tipo_falla_activo[tipo_falla_activo['tipo_falla_id'].isna()]['descripcion'].value_counts()

descripcion
rutina realizada, todo en orden                26
cumplido                                       21
se realizó tarea programada                    19
pendiente revisión adicional                   17
OK sin observaciones                           16
s/n                                            11
tarea de rutina según plan                     11
pérdida reportada por turno noche               5
reparación de urgencia                          4
s/observaciones                                 3
intervención según diagnóstico previo           3
falla en arranque                               3
falla detectada por operador, se interviene     2
para por alarma                                 1
detectado ruido anormal                         1
PARADA IMPREVISTA                               1
Name: count, dtype: int64

Las fallas con tipo_falla_id nulo se dan en todo el espectro de equipamientos, de tipos de mantenimiento y las descripciones de falla parecen indicar que se trata de tipos de falla que no se han clasificado, se podrian tratar estas filas como casos sin clasificación de tipo de falla.

Explorar tabla **tipo_activo**

In [7]:

%%sql

SELECT tipo_activo_id, 
        COUNT(*),
FROM tipo_activo
GROUP BY tipo_activo_id
HAVING COUNT(*) > 1;

Empty DataFrame
Columns: [tipo_activo_id, count_star()]
Index: []

Explorar tabla **activos**